##############################################################################
# DATABASE CONFIGURATION DATA
[database]

connection_string = "mongodb://localhost:27017"

###############################################################################
# HTTP server configuration

[http]

http_addr = ":3000"

[https]

https_addr = ":443"
###############################################################################

